name: dotnet
on:
  push:
  pull_request:
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test --nologo --configuration Release --verbosity quiet | tee --append $GITHUB_STEP_SUMMARY
